name: Auto-generate Command Docs

permissions:
  contents: write

on:
  push:
    paths:
      - '**.cs' # Only run when C# files change

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET 10
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '10.0.x'

      - name: Generate MD
        run: dotnet run .github/scripts/GenerateDocs.cs

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/docs/COMMANDS.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore(docs): Auto-generate command list [skip ci]"
          git push